# This is a basic workflow to help you get started with Actions

name: test

# Controls when the workflow will run
on: 
  # Triggers the workflow on push or pull request events but only for the makser branch
  push:
    branches: [ makser ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: install libs
        run: | 
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install gcovr
        
      - name: get tools version
        run: | 
          cmake --version
          make --version
          gcovr --version
        
      - name: build
        run: |
          cmake -B build/.dump -S .
          cmake --build build/.dump
          
      - name: test
        run: ctest

      - name: generate Docs/Coverage
        run: mkdir Docs/Coverage/Html
        run: mkdir Docs/Coverage/Sonarqube
        run: | 
        -r . -f src --html-details Docs/Coverage/Html/coverage.html \
        --sonarqube Docs/Coverage/Sonarqube/coverage.yml -o gcovfile/gcov
        
      - name: Commit report
        run: |
          git config --global user.name 'Filip-Pesula'
          git config --global user.email 'filip.pesula@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git checkout "${GITHUB_REF:11}"
          git add -f Docs/
          git commit -am "Automated report"
          git push

