# This is a basic workflow to help you get started with Actions

name: Build-Test

# Controls when the workflow will run
on: 
  # Triggers the workflow on push or pull request events but only for the makser branch
  
  pull_request:
    branches: [ makser ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: install libs
        run: | 
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install gcovr
      - run: |
          curl "https://{GIT_USER}:${GIT_TOKEN}@api.github.com/repos/${ORG_NAME}/${PROJECT_NAME}/statuses/${COMMIT_SHA}" -d "{\"state\": \"pending\",\"target_url\": \"https://github.com/${ORG_NAME}/${PROJECT_NAME}/pull/${PULL_NUMBER}/checks?check_run_id=${RUN_ID}\",\"description\": \"in progress — This check has started... \",\"context\": \"code cov\"}"

      - name: get tools version
        run: | 
          cmake --version
          make --version
          gcovr --version
        
      - name: build
        run: |
          cmake -B build/.dump -S .
          cmake --build build/.dump
          
      - name: test
        run: ctest
        
      - name: coverage
        run: |
          total="$(gcovr -r . -f src | grep TOTAL | grep -o '[^ ]\+$' | grep -o '[^%]\+') "
          echo "coverage: $total"
          echo $(echo "$total > 70" |bc -l)
          if (( $(echo "$total > 70" |bc -l) )); then
            echo "coverage OK"
            #curl "https://${GIT_USER}:${ADIKA_GITHUB_TOKEN}@api.github.com/repos/${ORG_NAME}/${PROJECT_NAME}/statuses/${COMMIT_SHA}" -d "{\"state\": \"${STATE}\",\"target_url\": \"https://github.com/${ORG_NAME}/${PROJECT_NAME}/pull/${PULL_NUMBER}/checks?check_run_id=${RUN_ID}\",\"description\": \"${total}%\",\"context\": \"code cov\"}"
          else
            echo "coverage NOK"
            #curl "https://${GIT_USER}:${ADIKA_GITHUB_TOKEN}@api.github.com/repos/${ORG_NAME}/${PROJECT_NAME}/statuses/${COMMIT_SHA}" -d "{\"state\": \"${STATE}\",\"target_url\": \"https://github.com/${ORG_NAME}/${PROJECT_NAME}/pull/${PULL_NUMBER}/checks?check_run_id=${RUN_ID}\",\"description\": \"not enough coverage ${total}%\",\"context\": \"code cov\"}"
            exit 1
          fi

